#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap no &
nitrogen --restore &
picom &
$HOME/.config/polybar/launch.sh &

xrandr |grep ' connected'|cut -f 1 -d ' '|while read display;do xrandr --output $display --set TearFree on;done
xinput set-prop 12 310 1
xinput set-prop 12 289 1
xinput set-prop 12 318 0

bspc monitor -d 1 2 3 4 5

bspc config border_width 		0
bspc config window_gap			20
bspc config split_ratio			0.5
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config normal_border_color		"#3c3836"
bspc config active_border_color		"#3c3836"
bspc config focused_border_color	"#3c3836"
bspc config focus_follows_pointer	true

